services:

  api-gateway:
    build: ./api-gateway
    ports:
      - "8000:8000"

  user-api:
    build: ./sync/user-api
    ports:
      - "8001:8000"

  book-api:
    build: ./sync/book-api
    ports:
      - "8002:8000"

  loan-api:
    build: ./sync/loan-api
    ports:
      - "8003:8000"

  fine-api:
    build: ./sync/fine-api
    ports:
      - "8004:8000"

  user-worker:
    build: ./async/user-worker
    # command: php artisan queue:work

  book-worker:
    build: ./async/book-worker
    # command: php artisan queue:work

  loan-worker:
    build: ./async/loan-worker
    # command: php artisan queue:work

  fine-worker:
    build: ./async/fine-worker
    # command: php artisan queue:work

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  mysql_data:
